// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEmailEventsByType = `-- name: CountEmailEventsByType :many
SELECT event_type, COUNT(*) as count FROM email_events WHERE org_id = $1 AND occurred_at >= $2 AND occurred_at <= $3 GROUP BY event_type
`

type CountEmailEventsByTypeParams struct {
	OrgID        uuid.UUID `json:"org_id"`
	OccurredAt   time.Time `json:"occurred_at"`
	OccurredAt_2 time.Time `json:"occurred_at_2"`
}

type CountEmailEventsByTypeRow struct {
	EventType string `json:"event_type"`
	Count     int64  `json:"count"`
}

func (q *Queries) CountEmailEventsByType(ctx context.Context, arg CountEmailEventsByTypeParams) ([]CountEmailEventsByTypeRow, error) {
	rows, err := q.db.Query(ctx, countEmailEventsByType, arg.OrgID, arg.OccurredAt, arg.OccurredAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEmailEventsByTypeRow{}
	for rows.Next() {
		var i CountEmailEventsByTypeRow
		if err := rows.Scan(&i.EventType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageDaily = `-- name: GetUsageDaily :many
SELECT id, org_id, date, emails_sent, emails_delivered, emails_bounced, emails_received, api_calls FROM usage_daily WHERE org_id = $1 AND date >= $2 AND date <= $3 ORDER BY date
`

type GetUsageDailyParams struct {
	OrgID  uuid.UUID   `json:"org_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

func (q *Queries) GetUsageDaily(ctx context.Context, arg GetUsageDailyParams) ([]UsageDaily, error) {
	rows, err := q.db.Query(ctx, getUsageDaily, arg.OrgID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageDaily{}
	for rows.Next() {
		var i UsageDaily
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Date,
			&i.EmailsSent,
			&i.EmailsDelivered,
			&i.EmailsBounced,
			&i.EmailsReceived,
			&i.ApiCalls,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageSummary = `-- name: GetUsageSummary :one
SELECT
  COALESCE(SUM(emails_sent), 0)::int as total_sent,
  COALESCE(SUM(emails_delivered), 0)::int as total_delivered,
  COALESCE(SUM(emails_bounced), 0)::int as total_bounced,
  COALESCE(SUM(emails_received), 0)::int as total_received
FROM usage_daily WHERE org_id = $1 AND date >= $2 AND date <= $3
`

type GetUsageSummaryParams struct {
	OrgID  uuid.UUID   `json:"org_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type GetUsageSummaryRow struct {
	TotalSent      int32 `json:"total_sent"`
	TotalDelivered int32 `json:"total_delivered"`
	TotalBounced   int32 `json:"total_bounced"`
	TotalReceived  int32 `json:"total_received"`
}

func (q *Queries) GetUsageSummary(ctx context.Context, arg GetUsageSummaryParams) (GetUsageSummaryRow, error) {
	row := q.db.QueryRow(ctx, getUsageSummary, arg.OrgID, arg.Date, arg.Date_2)
	var i GetUsageSummaryRow
	err := row.Scan(
		&i.TotalSent,
		&i.TotalDelivered,
		&i.TotalBounced,
		&i.TotalReceived,
	)
	return i, err
}

const upsertUsageDaily = `-- name: UpsertUsageDaily :exec
INSERT INTO usage_daily (org_id, date, emails_sent, emails_delivered, emails_bounced, emails_received, api_calls)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (org_id, date) DO UPDATE SET
  emails_sent = usage_daily.emails_sent + EXCLUDED.emails_sent,
  emails_delivered = usage_daily.emails_delivered + EXCLUDED.emails_delivered,
  emails_bounced = usage_daily.emails_bounced + EXCLUDED.emails_bounced,
  emails_received = usage_daily.emails_received + EXCLUDED.emails_received,
  api_calls = usage_daily.api_calls + EXCLUDED.api_calls
`

type UpsertUsageDailyParams struct {
	OrgID           uuid.UUID   `json:"org_id"`
	Date            pgtype.Date `json:"date"`
	EmailsSent      int32       `json:"emails_sent"`
	EmailsDelivered int32       `json:"emails_delivered"`
	EmailsBounced   int32       `json:"emails_bounced"`
	EmailsReceived  int32       `json:"emails_received"`
	ApiCalls        int32       `json:"api_calls"`
}

func (q *Queries) UpsertUsageDaily(ctx context.Context, arg UpsertUsageDailyParams) error {
	_, err := q.db.Exec(ctx, upsertUsageDaily,
		arg.OrgID,
		arg.Date,
		arg.EmailsSent,
		arg.EmailsDelivered,
		arg.EmailsBounced,
		arg.EmailsReceived,
		arg.ApiCalls,
	)
	return err
}
