// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (org_id, domain_id, name, prefix, key_hash, permission, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, domain_id, name, prefix, key_hash, permission, last_used_at, expires_at, created_at, revoked_at
`

type CreateAPIKeyParams struct {
	OrgID      uuid.UUID          `json:"org_id"`
	DomainID   pgtype.UUID        `json:"domain_id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	KeyHash    string             `json:"key_hash"`
	Permission string             `json:"permission"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.OrgID,
		arg.DomainID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
		arg.Permission,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DomainID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Permission,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, org_id, domain_id, name, prefix, key_hash, permission, last_used_at, expires_at, created_at, revoked_at FROM api_keys WHERE id = $1 AND org_id = $2
`

type GetAPIKeyParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, arg.ID, arg.OrgID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DomainID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Permission,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, org_id, domain_id, name, prefix, key_hash, permission, last_used_at, expires_at, created_at, revoked_at FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DomainID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Permission,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeysByOrg = `-- name: ListAPIKeysByOrg :many
SELECT id, org_id, domain_id, name, prefix, key_hash, permission, last_used_at, expires_at, created_at, revoked_at FROM api_keys
WHERE org_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByOrg(ctx context.Context, orgID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DomainID,
			&i.Name,
			&i.Prefix,
			&i.KeyHash,
			&i.Permission,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked_at = NOW() WHERE id = $1 AND org_id = $2
`

type RevokeAPIKeyParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.OrgID)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}
