// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs WHERE org_id = $1
`

func (q *Queries) CountAuditLogs(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (org_id, user_id, api_key_id, action, resource_type, resource_id, metadata, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $9::inet, $8)
RETURNING id, org_id, user_id, api_key_id, action, resource_type, resource_id, metadata, ip_address, user_agent, created_at
`

type CreateAuditLogParams struct {
	OrgID        uuid.UUID   `json:"org_id"`
	UserID       pgtype.UUID `json:"user_id"`
	ApiKeyID     pgtype.UUID `json:"api_key_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	Metadata     []byte      `json:"metadata"`
	UserAgent    pgtype.Text `json:"user_agent"`
	IpAddress    string      `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.OrgID,
		arg.UserID,
		arg.ApiKeyID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.ApiKeyID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Metadata,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLog = `-- name: GetAuditLog :one
SELECT id, org_id, user_id, api_key_id, action, resource_type, resource_id, metadata, ip_address, user_agent, created_at FROM audit_logs WHERE id = $1 AND org_id = $2
`

type GetAuditLogParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetAuditLog(ctx context.Context, arg GetAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLog, arg.ID, arg.OrgID)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.ApiKeyID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Metadata,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, org_id, user_id, api_key_id, action, resource_type, resource_id, metadata, ip_address, user_agent, created_at FROM audit_logs WHERE org_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListAuditLogsParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.ApiKeyID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
