// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentMonthUsage = `-- name: GetCurrentMonthUsage :one
SELECT COALESCE(SUM(emails_sent), 0)::int as total_sent,
       COALESCE(SUM(emails_received), 0)::int as total_received,
       COALESCE(SUM(api_calls), 0)::int as total_api_calls
FROM usage_daily
WHERE org_id = $1
  AND date >= date_trunc('month', CURRENT_DATE)::date
  AND date <= CURRENT_DATE
`

type GetCurrentMonthUsageRow struct {
	TotalSent     int32 `json:"total_sent"`
	TotalReceived int32 `json:"total_received"`
	TotalApiCalls int32 `json:"total_api_calls"`
}

func (q *Queries) GetCurrentMonthUsage(ctx context.Context, orgID uuid.UUID) (GetCurrentMonthUsageRow, error) {
	row := q.db.QueryRow(ctx, getCurrentMonthUsage, orgID)
	var i GetCurrentMonthUsageRow
	err := row.Scan(&i.TotalSent, &i.TotalReceived, &i.TotalApiCalls)
	return i, err
}

const getMonthlyUsageHistory = `-- name: GetMonthlyUsageHistory :many
SELECT id, org_id, month, total_sent, total_received, total_api_calls, plan_limit, overage_count FROM usage_monthly WHERE org_id = $1 ORDER BY month DESC LIMIT $2
`

type GetMonthlyUsageHistoryParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Limit int32     `json:"limit"`
}

func (q *Queries) GetMonthlyUsageHistory(ctx context.Context, arg GetMonthlyUsageHistoryParams) ([]UsageMonthly, error) {
	rows, err := q.db.Query(ctx, getMonthlyUsageHistory, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageMonthly{}
	for rows.Next() {
		var i UsageMonthly
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Month,
			&i.TotalSent,
			&i.TotalReceived,
			&i.TotalApiCalls,
			&i.PlanLimit,
			&i.OverageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUsageMonthly = `-- name: UpsertUsageMonthly :exec
INSERT INTO usage_monthly (org_id, month, total_sent, total_received, total_api_calls, plan_limit, overage_count)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (org_id, month) DO UPDATE SET
  total_sent = EXCLUDED.total_sent,
  total_received = EXCLUDED.total_received,
  total_api_calls = EXCLUDED.total_api_calls,
  overage_count = EXCLUDED.overage_count
`

type UpsertUsageMonthlyParams struct {
	OrgID         uuid.UUID   `json:"org_id"`
	Month         pgtype.Date `json:"month"`
	TotalSent     int32       `json:"total_sent"`
	TotalReceived int32       `json:"total_received"`
	TotalApiCalls int32       `json:"total_api_calls"`
	PlanLimit     int32       `json:"plan_limit"`
	OverageCount  int32       `json:"overage_count"`
}

func (q *Queries) UpsertUsageMonthly(ctx context.Context, arg UpsertUsageMonthlyParams) error {
	_, err := q.db.Exec(ctx, upsertUsageMonthly,
		arg.OrgID,
		arg.Month,
		arg.TotalSent,
		arg.TotalReceived,
		arg.TotalApiCalls,
		arg.PlanLimit,
		arg.OverageCount,
	)
	return err
}
