// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domains.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDNSRecord = `-- name: CreateDNSRecord :one
INSERT INTO dns_records (domain_id, record_type, host, value, purpose) VALUES ($1, $2, $3, $4, $5) RETURNING id, domain_id, record_type, host, value, purpose, status, verified_at, created_at
`

type CreateDNSRecordParams struct {
	DomainID   uuid.UUID `json:"domain_id"`
	RecordType string    `json:"record_type"`
	Host       string    `json:"host"`
	Value      string    `json:"value"`
	Purpose    string    `json:"purpose"`
}

func (q *Queries) CreateDNSRecord(ctx context.Context, arg CreateDNSRecordParams) (DnsRecord, error) {
	row := q.db.QueryRow(ctx, createDNSRecord,
		arg.DomainID,
		arg.RecordType,
		arg.Host,
		arg.Value,
		arg.Purpose,
	)
	var i DnsRecord
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.RecordType,
		&i.Host,
		&i.Value,
		&i.Purpose,
		&i.Status,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (org_id, name, dkim_private_key, dkim_selector)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, name, status, region, dkim_private_key, dkim_selector, open_tracking, click_tracking, cloudflare_zone_id, cloudflare_api_token_enc, verified_at, created_at, updated_at
`

type CreateDomainParams struct {
	OrgID          uuid.UUID   `json:"org_id"`
	Name           string      `json:"name"`
	DkimPrivateKey pgtype.Text `json:"dkim_private_key"`
	DkimSelector   string      `json:"dkim_selector"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain,
		arg.OrgID,
		arg.Name,
		arg.DkimPrivateKey,
		arg.DkimSelector,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.Region,
		&i.DkimPrivateKey,
		&i.DkimSelector,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.CloudflareZoneID,
		&i.CloudflareApiTokenEnc,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDNSRecordsByDomain = `-- name: DeleteDNSRecordsByDomain :exec
DELETE FROM dns_records WHERE domain_id = $1
`

func (q *Queries) DeleteDNSRecordsByDomain(ctx context.Context, domainID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDNSRecordsByDomain, domainID)
	return err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains WHERE id = $1 AND org_id = $2
`

type DeleteDomainParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteDomain(ctx context.Context, arg DeleteDomainParams) error {
	_, err := q.db.Exec(ctx, deleteDomain, arg.ID, arg.OrgID)
	return err
}

const getDomain = `-- name: GetDomain :one
SELECT id, org_id, name, status, region, dkim_private_key, dkim_selector, open_tracking, click_tracking, cloudflare_zone_id, cloudflare_api_token_enc, verified_at, created_at, updated_at FROM domains WHERE id = $1 AND org_id = $2
`

type GetDomainParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetDomain(ctx context.Context, arg GetDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomain, arg.ID, arg.OrgID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.Region,
		&i.DkimPrivateKey,
		&i.DkimSelector,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.CloudflareZoneID,
		&i.CloudflareApiTokenEnc,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainByName = `-- name: GetDomainByName :one
SELECT id, org_id, name, status, region, dkim_private_key, dkim_selector, open_tracking, click_tracking, cloudflare_zone_id, cloudflare_api_token_enc, verified_at, created_at, updated_at FROM domains WHERE name = $1 AND org_id = $2
`

type GetDomainByNameParams struct {
	Name  string    `json:"name"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetDomainByName(ctx context.Context, arg GetDomainByNameParams) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByName, arg.Name, arg.OrgID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.Region,
		&i.DkimPrivateKey,
		&i.DkimSelector,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.CloudflareZoneID,
		&i.CloudflareApiTokenEnc,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDNSRecordsByDomain = `-- name: ListDNSRecordsByDomain :many
SELECT id, domain_id, record_type, host, value, purpose, status, verified_at, created_at FROM dns_records WHERE domain_id = $1 ORDER BY purpose
`

func (q *Queries) ListDNSRecordsByDomain(ctx context.Context, domainID uuid.UUID) ([]DnsRecord, error) {
	rows, err := q.db.Query(ctx, listDNSRecordsByDomain, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsRecord{}
	for rows.Next() {
		var i DnsRecord
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.RecordType,
			&i.Host,
			&i.Value,
			&i.Purpose,
			&i.Status,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsByOrg = `-- name: ListDomainsByOrg :many
SELECT id, org_id, name, status, region, dkim_private_key, dkim_selector, open_tracking, click_tracking, cloudflare_zone_id, cloudflare_api_token_enc, verified_at, created_at, updated_at FROM domains WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDomainsByOrg(ctx context.Context, orgID uuid.UUID) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomainsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Status,
			&i.Region,
			&i.DkimPrivateKey,
			&i.DkimSelector,
			&i.OpenTracking,
			&i.ClickTracking,
			&i.CloudflareZoneID,
			&i.CloudflareApiTokenEnc,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDNSRecordStatus = `-- name: UpdateDNSRecordStatus :exec
UPDATE dns_records SET status = $2, verified_at = CASE WHEN $2 = 'verified' THEN NOW() ELSE verified_at END WHERE id = $1
`

type UpdateDNSRecordStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDNSRecordStatus(ctx context.Context, arg UpdateDNSRecordStatusParams) error {
	_, err := q.db.Exec(ctx, updateDNSRecordStatus, arg.ID, arg.Status)
	return err
}

const updateDomainCloudflare = `-- name: UpdateDomainCloudflare :exec
UPDATE domains SET cloudflare_zone_id = $3, cloudflare_api_token_enc = $4 WHERE id = $1 AND org_id = $2
`

type UpdateDomainCloudflareParams struct {
	ID                    uuid.UUID   `json:"id"`
	OrgID                 uuid.UUID   `json:"org_id"`
	CloudflareZoneID      pgtype.Text `json:"cloudflare_zone_id"`
	CloudflareApiTokenEnc pgtype.Text `json:"cloudflare_api_token_enc"`
}

func (q *Queries) UpdateDomainCloudflare(ctx context.Context, arg UpdateDomainCloudflareParams) error {
	_, err := q.db.Exec(ctx, updateDomainCloudflare,
		arg.ID,
		arg.OrgID,
		arg.CloudflareZoneID,
		arg.CloudflareApiTokenEnc,
	)
	return err
}

const updateDomainSettings = `-- name: UpdateDomainSettings :one
UPDATE domains SET open_tracking = $3, click_tracking = $4 WHERE id = $1 AND org_id = $2 RETURNING id, org_id, name, status, region, dkim_private_key, dkim_selector, open_tracking, click_tracking, cloudflare_zone_id, cloudflare_api_token_enc, verified_at, created_at, updated_at
`

type UpdateDomainSettingsParams struct {
	ID            uuid.UUID `json:"id"`
	OrgID         uuid.UUID `json:"org_id"`
	OpenTracking  bool      `json:"open_tracking"`
	ClickTracking bool      `json:"click_tracking"`
}

func (q *Queries) UpdateDomainSettings(ctx context.Context, arg UpdateDomainSettingsParams) (Domain, error) {
	row := q.db.QueryRow(ctx, updateDomainSettings,
		arg.ID,
		arg.OrgID,
		arg.OpenTracking,
		arg.ClickTracking,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.Region,
		&i.DkimPrivateKey,
		&i.DkimSelector,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.CloudflareZoneID,
		&i.CloudflareApiTokenEnc,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDomainStatus = `-- name: UpdateDomainStatus :exec
UPDATE domains SET status = $3, verified_at = CASE WHEN $3 = 'verified' THEN NOW() ELSE verified_at END WHERE id = $1 AND org_id = $2
`

type UpdateDomainStatusParams struct {
	ID     uuid.UUID `json:"id"`
	OrgID  uuid.UUID `json:"org_id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDomainStatus(ctx context.Context, arg UpdateDomainStatusParams) error {
	_, err := q.db.Exec(ctx, updateDomainStatus, arg.ID, arg.OrgID, arg.Status)
	return err
}
