// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: emails.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEmailsByOrg = `-- name: CountEmailsByOrg :one
SELECT COUNT(*) FROM emails WHERE org_id = $1
`

func (q *Queries) CountEmailsByOrg(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEmailsByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmail = `-- name: CreateEmail :one
INSERT INTO emails (org_id, domain_id, api_key_id, idempotency_key, from_address, from_name, to_addresses, cc_addresses, bcc_addresses, reply_to, subject, text_body_key, html_body_key, headers, tags, template_id, template_data, status, scheduled_at, message_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
RETURNING id, org_id, domain_id, api_key_id, idempotency_key, from_address, from_name, to_addresses, cc_addresses, bcc_addresses, reply_to, subject, text_body_key, html_body_key, headers, tags, template_id, template_data, status, scheduled_at, sent_at, delivered_at, message_id, created_at
`

type CreateEmailParams struct {
	OrgID          uuid.UUID          `json:"org_id"`
	DomainID       uuid.UUID          `json:"domain_id"`
	ApiKeyID       pgtype.UUID        `json:"api_key_id"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	FromAddress    string             `json:"from_address"`
	FromName       pgtype.Text        `json:"from_name"`
	ToAddresses    json.RawMessage    `json:"to_addresses"`
	CcAddresses    []byte             `json:"cc_addresses"`
	BccAddresses   []byte             `json:"bcc_addresses"`
	ReplyTo        pgtype.Text        `json:"reply_to"`
	Subject        string             `json:"subject"`
	TextBodyKey    pgtype.Text        `json:"text_body_key"`
	HtmlBodyKey    pgtype.Text        `json:"html_body_key"`
	Headers        []byte             `json:"headers"`
	Tags           []byte             `json:"tags"`
	TemplateID     pgtype.UUID        `json:"template_id"`
	TemplateData   []byte             `json:"template_data"`
	Status         string             `json:"status"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	MessageID      pgtype.Text        `json:"message_id"`
}

func (q *Queries) CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error) {
	row := q.db.QueryRow(ctx, createEmail,
		arg.OrgID,
		arg.DomainID,
		arg.ApiKeyID,
		arg.IdempotencyKey,
		arg.FromAddress,
		arg.FromName,
		arg.ToAddresses,
		arg.CcAddresses,
		arg.BccAddresses,
		arg.ReplyTo,
		arg.Subject,
		arg.TextBodyKey,
		arg.HtmlBodyKey,
		arg.Headers,
		arg.Tags,
		arg.TemplateID,
		arg.TemplateData,
		arg.Status,
		arg.ScheduledAt,
		arg.MessageID,
	)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DomainID,
		&i.ApiKeyID,
		&i.IdempotencyKey,
		&i.FromAddress,
		&i.FromName,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.ReplyTo,
		&i.Subject,
		&i.TextBodyKey,
		&i.HtmlBodyKey,
		&i.Headers,
		&i.Tags,
		&i.TemplateID,
		&i.TemplateData,
		&i.Status,
		&i.ScheduledAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.MessageID,
		&i.CreatedAt,
	)
	return i, err
}

const getEmail = `-- name: GetEmail :one
SELECT id, org_id, domain_id, api_key_id, idempotency_key, from_address, from_name, to_addresses, cc_addresses, bcc_addresses, reply_to, subject, text_body_key, html_body_key, headers, tags, template_id, template_data, status, scheduled_at, sent_at, delivered_at, message_id, created_at FROM emails WHERE id = $1 AND org_id = $2
`

type GetEmailParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetEmail(ctx context.Context, arg GetEmailParams) (Email, error) {
	row := q.db.QueryRow(ctx, getEmail, arg.ID, arg.OrgID)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DomainID,
		&i.ApiKeyID,
		&i.IdempotencyKey,
		&i.FromAddress,
		&i.FromName,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.ReplyTo,
		&i.Subject,
		&i.TextBodyKey,
		&i.HtmlBodyKey,
		&i.Headers,
		&i.Tags,
		&i.TemplateID,
		&i.TemplateData,
		&i.Status,
		&i.ScheduledAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.MessageID,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailByIdempotencyKey = `-- name: GetEmailByIdempotencyKey :one
SELECT id, org_id, domain_id, api_key_id, idempotency_key, from_address, from_name, to_addresses, cc_addresses, bcc_addresses, reply_to, subject, text_body_key, html_body_key, headers, tags, template_id, template_data, status, scheduled_at, sent_at, delivered_at, message_id, created_at FROM emails WHERE org_id = $1 AND idempotency_key = $2
`

type GetEmailByIdempotencyKeyParams struct {
	OrgID          uuid.UUID   `json:"org_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) GetEmailByIdempotencyKey(ctx context.Context, arg GetEmailByIdempotencyKeyParams) (Email, error) {
	row := q.db.QueryRow(ctx, getEmailByIdempotencyKey, arg.OrgID, arg.IdempotencyKey)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DomainID,
		&i.ApiKeyID,
		&i.IdempotencyKey,
		&i.FromAddress,
		&i.FromName,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.ReplyTo,
		&i.Subject,
		&i.TextBodyKey,
		&i.HtmlBodyKey,
		&i.Headers,
		&i.Tags,
		&i.TemplateID,
		&i.TemplateData,
		&i.Status,
		&i.ScheduledAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.MessageID,
		&i.CreatedAt,
	)
	return i, err
}

const getVerifiedDomainByName = `-- name: GetVerifiedDomainByName :one
SELECT id, org_id, name, status, region, dkim_private_key, dkim_selector, open_tracking, click_tracking, cloudflare_zone_id, cloudflare_api_token_enc, verified_at, created_at, updated_at FROM domains WHERE name = $1 AND org_id = $2 AND status = 'verified'
`

type GetVerifiedDomainByNameParams struct {
	Name  string    `json:"name"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetVerifiedDomainByName(ctx context.Context, arg GetVerifiedDomainByNameParams) (Domain, error) {
	row := q.db.QueryRow(ctx, getVerifiedDomainByName, arg.Name, arg.OrgID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.Region,
		&i.DkimPrivateKey,
		&i.DkimSelector,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.CloudflareZoneID,
		&i.CloudflareApiTokenEnc,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmailsByOrg = `-- name: ListEmailsByOrg :many
SELECT id, org_id, domain_id, api_key_id, idempotency_key, from_address, from_name, to_addresses, cc_addresses, bcc_addresses, reply_to, subject, text_body_key, html_body_key, headers, tags, template_id, template_data, status, scheduled_at, sent_at, delivered_at, message_id, created_at FROM emails WHERE org_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListEmailsByOrgParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListEmailsByOrg(ctx context.Context, arg ListEmailsByOrgParams) ([]Email, error) {
	rows, err := q.db.Query(ctx, listEmailsByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Email{}
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DomainID,
			&i.ApiKeyID,
			&i.IdempotencyKey,
			&i.FromAddress,
			&i.FromName,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.BccAddresses,
			&i.ReplyTo,
			&i.Subject,
			&i.TextBodyKey,
			&i.HtmlBodyKey,
			&i.Headers,
			&i.Tags,
			&i.TemplateID,
			&i.TemplateData,
			&i.Status,
			&i.ScheduledAt,
			&i.SentAt,
			&i.DeliveredAt,
			&i.MessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailStatus = `-- name: UpdateEmailStatus :exec
UPDATE emails SET status = $2, sent_at = CASE WHEN $2 = 'sent' THEN NOW() ELSE sent_at END, delivered_at = CASE WHEN $2 = 'delivered' THEN NOW() ELSE delivered_at END WHERE id = $1
`

type UpdateEmailStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateEmailStatus(ctx context.Context, arg UpdateEmailStatusParams) error {
	_, err := q.db.Exec(ctx, updateEmailStatus, arg.ID, arg.Status)
	return err
}
