// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_events.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEmailEventsByOrg = `-- name: CountEmailEventsByOrg :one
SELECT COUNT(*) FROM email_events WHERE org_id = $1
`

func (q *Queries) CountEmailEventsByOrg(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEmailEventsByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailEvent = `-- name: CreateEmailEvent :one
INSERT INTO email_events (email_id, org_id, event_type, recipient, metadata, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $7::inet, $6)
RETURNING id, email_id, org_id, event_type, recipient, metadata, ip_address, user_agent, occurred_at
`

type CreateEmailEventParams struct {
	EmailID   uuid.UUID   `json:"email_id"`
	OrgID     uuid.UUID   `json:"org_id"`
	EventType string      `json:"event_type"`
	Recipient string      `json:"recipient"`
	Metadata  []byte      `json:"metadata"`
	UserAgent pgtype.Text `json:"user_agent"`
	IpAddress string      `json:"ip_address"`
}

func (q *Queries) CreateEmailEvent(ctx context.Context, arg CreateEmailEventParams) (EmailEvent, error) {
	row := q.db.QueryRow(ctx, createEmailEvent,
		arg.EmailID,
		arg.OrgID,
		arg.EventType,
		arg.Recipient,
		arg.Metadata,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i EmailEvent
	err := row.Scan(
		&i.ID,
		&i.EmailID,
		&i.OrgID,
		&i.EventType,
		&i.Recipient,
		&i.Metadata,
		&i.IpAddress,
		&i.UserAgent,
		&i.OccurredAt,
	)
	return i, err
}

const listEmailEvents = `-- name: ListEmailEvents :many
SELECT id, email_id, org_id, event_type, recipient, metadata, ip_address, user_agent, occurred_at FROM email_events WHERE email_id = $1 ORDER BY occurred_at ASC
`

func (q *Queries) ListEmailEvents(ctx context.Context, emailID uuid.UUID) ([]EmailEvent, error) {
	rows, err := q.db.Query(ctx, listEmailEvents, emailID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailEvent{}
	for rows.Next() {
		var i EmailEvent
		if err := rows.Scan(
			&i.ID,
			&i.EmailID,
			&i.OrgID,
			&i.EventType,
			&i.Recipient,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailEventsByOrg = `-- name: ListEmailEventsByOrg :many
SELECT id, email_id, org_id, event_type, recipient, metadata, ip_address, user_agent, occurred_at FROM email_events WHERE org_id = $1 ORDER BY occurred_at DESC LIMIT $2 OFFSET $3
`

type ListEmailEventsByOrgParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListEmailEventsByOrg(ctx context.Context, arg ListEmailEventsByOrgParams) ([]EmailEvent, error) {
	rows, err := q.db.Query(ctx, listEmailEventsByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailEvent{}
	for rows.Next() {
		var i EmailEvent
		if err := rows.Scan(
			&i.ID,
			&i.EmailID,
			&i.OrgID,
			&i.EventType,
			&i.Recipient,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
