// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox.sql

package sqlcdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMessageLabel = `-- name: AddMessageLabel :exec
INSERT INTO inbox_message_labels (message_id, label_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddMessageLabelParams struct {
	MessageID uuid.UUID `json:"message_id"`
	LabelID   uuid.UUID `json:"label_id"`
}

func (q *Queries) AddMessageLabel(ctx context.Context, arg AddMessageLabelParams) error {
	_, err := q.db.Exec(ctx, addMessageLabel, arg.MessageID, arg.LabelID)
	return err
}

const countThreads = `-- name: CountThreads :one
SELECT COUNT(*) FROM inbox_threads WHERE org_id = $1
`

func (q *Queries) CountThreads(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countThreads, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInboxMessage = `-- name: CreateInboxMessage :one

INSERT INTO inbox_messages (org_id, domain_id, thread_id, message_id_header, in_reply_to, references_header, from_address, from_name, to_addresses, cc_addresses, subject, text_body_key, html_body_key, snippet, received_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, org_id, domain_id, thread_id, message_id_header, in_reply_to, references_header, from_address, from_name, to_addresses, cc_addresses, subject, text_body_key, html_body_key, snippet, is_read, is_starred, is_archived, is_trashed, received_at, created_at
`

type CreateInboxMessageParams struct {
	OrgID            uuid.UUID       `json:"org_id"`
	DomainID         uuid.UUID       `json:"domain_id"`
	ThreadID         pgtype.UUID     `json:"thread_id"`
	MessageIDHeader  pgtype.Text     `json:"message_id_header"`
	InReplyTo        pgtype.Text     `json:"in_reply_to"`
	ReferencesHeader pgtype.Text     `json:"references_header"`
	FromAddress      string          `json:"from_address"`
	FromName         pgtype.Text     `json:"from_name"`
	ToAddresses      json.RawMessage `json:"to_addresses"`
	CcAddresses      []byte          `json:"cc_addresses"`
	Subject          string          `json:"subject"`
	TextBodyKey      pgtype.Text     `json:"text_body_key"`
	HtmlBodyKey      pgtype.Text     `json:"html_body_key"`
	Snippet          pgtype.Text     `json:"snippet"`
	ReceivedAt       time.Time       `json:"received_at"`
}

// Messages
func (q *Queries) CreateInboxMessage(ctx context.Context, arg CreateInboxMessageParams) (InboxMessage, error) {
	row := q.db.QueryRow(ctx, createInboxMessage,
		arg.OrgID,
		arg.DomainID,
		arg.ThreadID,
		arg.MessageIDHeader,
		arg.InReplyTo,
		arg.ReferencesHeader,
		arg.FromAddress,
		arg.FromName,
		arg.ToAddresses,
		arg.CcAddresses,
		arg.Subject,
		arg.TextBodyKey,
		arg.HtmlBodyKey,
		arg.Snippet,
		arg.ReceivedAt,
	)
	var i InboxMessage
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DomainID,
		&i.ThreadID,
		&i.MessageIDHeader,
		&i.InReplyTo,
		&i.ReferencesHeader,
		&i.FromAddress,
		&i.FromName,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.Subject,
		&i.TextBodyKey,
		&i.HtmlBodyKey,
		&i.Snippet,
		&i.IsRead,
		&i.IsStarred,
		&i.IsArchived,
		&i.IsTrashed,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createLabel = `-- name: CreateLabel :one

INSERT INTO inbox_labels (org_id, name, color) VALUES ($1, $2, $3) RETURNING id, org_id, name, color, created_at
`

type CreateLabelParams struct {
	OrgID uuid.UUID   `json:"org_id"`
	Name  string      `json:"name"`
	Color pgtype.Text `json:"color"`
}

// Labels
func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (InboxLabel, error) {
	row := q.db.QueryRow(ctx, createLabel, arg.OrgID, arg.Name, arg.Color)
	var i InboxLabel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const createThread = `-- name: CreateThread :one

INSERT INTO inbox_threads (org_id, domain_id, subject, participant_addresses, last_message_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, domain_id, subject, participant_addresses, last_message_at, message_count, created_at
`

type CreateThreadParams struct {
	OrgID                uuid.UUID       `json:"org_id"`
	DomainID             uuid.UUID       `json:"domain_id"`
	Subject              string          `json:"subject"`
	ParticipantAddresses json.RawMessage `json:"participant_addresses"`
	LastMessageAt        time.Time       `json:"last_message_at"`
}

// Threads
func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (InboxThread, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.OrgID,
		arg.DomainID,
		arg.Subject,
		arg.ParticipantAddresses,
		arg.LastMessageAt,
	)
	var i InboxThread
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DomainID,
		&i.Subject,
		&i.ParticipantAddresses,
		&i.LastMessageAt,
		&i.MessageCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInboxMessage = `-- name: DeleteInboxMessage :exec
DELETE FROM inbox_messages WHERE id = $1 AND org_id = $2
`

type DeleteInboxMessageParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteInboxMessage(ctx context.Context, arg DeleteInboxMessageParams) error {
	_, err := q.db.Exec(ctx, deleteInboxMessage, arg.ID, arg.OrgID)
	return err
}

const deleteLabel = `-- name: DeleteLabel :exec
DELETE FROM inbox_labels WHERE id = $1 AND org_id = $2
`

type DeleteLabelParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteLabel(ctx context.Context, arg DeleteLabelParams) error {
	_, err := q.db.Exec(ctx, deleteLabel, arg.ID, arg.OrgID)
	return err
}

const deleteThread = `-- name: DeleteThread :exec
DELETE FROM inbox_threads WHERE id = $1 AND org_id = $2
`

type DeleteThreadParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteThread(ctx context.Context, arg DeleteThreadParams) error {
	_, err := q.db.Exec(ctx, deleteThread, arg.ID, arg.OrgID)
	return err
}

const findMessageByMessageID = `-- name: FindMessageByMessageID :one
SELECT id, org_id, domain_id, thread_id, message_id_header, in_reply_to, references_header, from_address, from_name, to_addresses, cc_addresses, subject, text_body_key, html_body_key, snippet, is_read, is_starred, is_archived, is_trashed, received_at, created_at FROM inbox_messages WHERE message_id_header = $1 AND org_id = $2
`

type FindMessageByMessageIDParams struct {
	MessageIDHeader pgtype.Text `json:"message_id_header"`
	OrgID           uuid.UUID   `json:"org_id"`
}

func (q *Queries) FindMessageByMessageID(ctx context.Context, arg FindMessageByMessageIDParams) (InboxMessage, error) {
	row := q.db.QueryRow(ctx, findMessageByMessageID, arg.MessageIDHeader, arg.OrgID)
	var i InboxMessage
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DomainID,
		&i.ThreadID,
		&i.MessageIDHeader,
		&i.InReplyTo,
		&i.ReferencesHeader,
		&i.FromAddress,
		&i.FromName,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.Subject,
		&i.TextBodyKey,
		&i.HtmlBodyKey,
		&i.Snippet,
		&i.IsRead,
		&i.IsStarred,
		&i.IsArchived,
		&i.IsTrashed,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findThreadBySubjectAndDomain = `-- name: FindThreadBySubjectAndDomain :one
SELECT id, org_id, domain_id, subject, participant_addresses, last_message_at, message_count, created_at FROM inbox_threads
WHERE org_id = $1 AND domain_id = $2 AND subject = $3 AND last_message_at > $4
ORDER BY last_message_at DESC
LIMIT 1
`

type FindThreadBySubjectAndDomainParams struct {
	OrgID         uuid.UUID `json:"org_id"`
	DomainID      uuid.UUID `json:"domain_id"`
	Subject       string    `json:"subject"`
	LastMessageAt time.Time `json:"last_message_at"`
}

func (q *Queries) FindThreadBySubjectAndDomain(ctx context.Context, arg FindThreadBySubjectAndDomainParams) (InboxThread, error) {
	row := q.db.QueryRow(ctx, findThreadBySubjectAndDomain,
		arg.OrgID,
		arg.DomainID,
		arg.Subject,
		arg.LastMessageAt,
	)
	var i InboxThread
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DomainID,
		&i.Subject,
		&i.ParticipantAddresses,
		&i.LastMessageAt,
		&i.MessageCount,
		&i.CreatedAt,
	)
	return i, err
}

const getInboxMessage = `-- name: GetInboxMessage :one
SELECT id, org_id, domain_id, thread_id, message_id_header, in_reply_to, references_header, from_address, from_name, to_addresses, cc_addresses, subject, text_body_key, html_body_key, snippet, is_read, is_starred, is_archived, is_trashed, received_at, created_at FROM inbox_messages WHERE id = $1 AND org_id = $2
`

type GetInboxMessageParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetInboxMessage(ctx context.Context, arg GetInboxMessageParams) (InboxMessage, error) {
	row := q.db.QueryRow(ctx, getInboxMessage, arg.ID, arg.OrgID)
	var i InboxMessage
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DomainID,
		&i.ThreadID,
		&i.MessageIDHeader,
		&i.InReplyTo,
		&i.ReferencesHeader,
		&i.FromAddress,
		&i.FromName,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.Subject,
		&i.TextBodyKey,
		&i.HtmlBodyKey,
		&i.Snippet,
		&i.IsRead,
		&i.IsStarred,
		&i.IsArchived,
		&i.IsTrashed,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT id, org_id, domain_id, subject, participant_addresses, last_message_at, message_count, created_at FROM inbox_threads WHERE id = $1 AND org_id = $2
`

type GetThreadParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetThread(ctx context.Context, arg GetThreadParams) (InboxThread, error) {
	row := q.db.QueryRow(ctx, getThread, arg.ID, arg.OrgID)
	var i InboxThread
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DomainID,
		&i.Subject,
		&i.ParticipantAddresses,
		&i.LastMessageAt,
		&i.MessageCount,
		&i.CreatedAt,
	)
	return i, err
}

const listLabelsByOrg = `-- name: ListLabelsByOrg :many
SELECT id, org_id, name, color, created_at FROM inbox_labels WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListLabelsByOrg(ctx context.Context, orgID uuid.UUID) ([]InboxLabel, error) {
	rows, err := q.db.Query(ctx, listLabelsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxLabel{}
	for rows.Next() {
		var i InboxLabel
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageLabels = `-- name: ListMessageLabels :many
SELECT il.id, il.org_id, il.name, il.color, il.created_at FROM inbox_labels il JOIN inbox_message_labels iml ON il.id = iml.label_id WHERE iml.message_id = $1
`

func (q *Queries) ListMessageLabels(ctx context.Context, messageID uuid.UUID) ([]InboxLabel, error) {
	rows, err := q.db.Query(ctx, listMessageLabels, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxLabel{}
	for rows.Next() {
		var i InboxLabel
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByThread = `-- name: ListMessagesByThread :many
SELECT id, org_id, domain_id, thread_id, message_id_header, in_reply_to, references_header, from_address, from_name, to_addresses, cc_addresses, subject, text_body_key, html_body_key, snippet, is_read, is_starred, is_archived, is_trashed, received_at, created_at FROM inbox_messages WHERE thread_id = $1 AND org_id = $2 ORDER BY received_at ASC
`

type ListMessagesByThreadParams struct {
	ThreadID pgtype.UUID `json:"thread_id"`
	OrgID    uuid.UUID   `json:"org_id"`
}

func (q *Queries) ListMessagesByThread(ctx context.Context, arg ListMessagesByThreadParams) ([]InboxMessage, error) {
	rows, err := q.db.Query(ctx, listMessagesByThread, arg.ThreadID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxMessage{}
	for rows.Next() {
		var i InboxMessage
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DomainID,
			&i.ThreadID,
			&i.MessageIDHeader,
			&i.InReplyTo,
			&i.ReferencesHeader,
			&i.FromAddress,
			&i.FromName,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.Subject,
			&i.TextBodyKey,
			&i.HtmlBodyKey,
			&i.Snippet,
			&i.IsRead,
			&i.IsStarred,
			&i.IsArchived,
			&i.IsTrashed,
			&i.ReceivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreads = `-- name: ListThreads :many
SELECT id, org_id, domain_id, subject, participant_addresses, last_message_at, message_count, created_at FROM inbox_threads WHERE org_id = $1 ORDER BY last_message_at DESC LIMIT $2 OFFSET $3
`

type ListThreadsParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListThreads(ctx context.Context, arg ListThreadsParams) ([]InboxThread, error) {
	rows, err := q.db.Query(ctx, listThreads, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxThread{}
	for rows.Next() {
		var i InboxThread
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DomainID,
			&i.Subject,
			&i.ParticipantAddresses,
			&i.LastMessageAt,
			&i.MessageCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageRead = `-- name: MarkMessageRead :exec
UPDATE inbox_messages SET is_read = true WHERE id = $1 AND org_id = $2
`

type MarkMessageReadParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) MarkMessageRead(ctx context.Context, arg MarkMessageReadParams) error {
	_, err := q.db.Exec(ctx, markMessageRead, arg.ID, arg.OrgID)
	return err
}

const removeMessageLabel = `-- name: RemoveMessageLabel :exec
DELETE FROM inbox_message_labels WHERE message_id = $1 AND label_id = $2
`

type RemoveMessageLabelParams struct {
	MessageID uuid.UUID `json:"message_id"`
	LabelID   uuid.UUID `json:"label_id"`
}

func (q *Queries) RemoveMessageLabel(ctx context.Context, arg RemoveMessageLabelParams) error {
	_, err := q.db.Exec(ctx, removeMessageLabel, arg.MessageID, arg.LabelID)
	return err
}

const searchMessages = `-- name: SearchMessages :many
SELECT id, org_id, domain_id, thread_id, message_id_header, in_reply_to, references_header, from_address, from_name, to_addresses, cc_addresses, subject, text_body_key, html_body_key, snippet, is_read, is_starred, is_archived, is_trashed, received_at, created_at FROM inbox_messages WHERE org_id = $1 AND subject ILIKE '%' || $2 || '%' ORDER BY received_at DESC LIMIT $3 OFFSET $4
`

type SearchMessagesParams struct {
	OrgID   uuid.UUID   `json:"org_id"`
	Column2 pgtype.Text `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]InboxMessage, error) {
	rows, err := q.db.Query(ctx, searchMessages,
		arg.OrgID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxMessage{}
	for rows.Next() {
		var i InboxMessage
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DomainID,
			&i.ThreadID,
			&i.MessageIDHeader,
			&i.InReplyTo,
			&i.ReferencesHeader,
			&i.FromAddress,
			&i.FromName,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.Subject,
			&i.TextBodyKey,
			&i.HtmlBodyKey,
			&i.Snippet,
			&i.IsRead,
			&i.IsStarred,
			&i.IsArchived,
			&i.IsTrashed,
			&i.ReceivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLabel = `-- name: UpdateLabel :one
UPDATE inbox_labels SET name = $3, color = $4 WHERE id = $1 AND org_id = $2 RETURNING id, org_id, name, color, created_at
`

type UpdateLabelParams struct {
	ID    uuid.UUID   `json:"id"`
	OrgID uuid.UUID   `json:"org_id"`
	Name  string      `json:"name"`
	Color pgtype.Text `json:"color"`
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) (InboxLabel, error) {
	row := q.db.QueryRow(ctx, updateLabel,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Color,
	)
	var i InboxLabel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const updateMessageFlags = `-- name: UpdateMessageFlags :exec
UPDATE inbox_messages SET is_read = $3, is_starred = $4, is_archived = $5, is_trashed = $6 WHERE id = $1 AND org_id = $2
`

type UpdateMessageFlagsParams struct {
	ID         uuid.UUID `json:"id"`
	OrgID      uuid.UUID `json:"org_id"`
	IsRead     bool      `json:"is_read"`
	IsStarred  bool      `json:"is_starred"`
	IsArchived bool      `json:"is_archived"`
	IsTrashed  bool      `json:"is_trashed"`
}

func (q *Queries) UpdateMessageFlags(ctx context.Context, arg UpdateMessageFlagsParams) error {
	_, err := q.db.Exec(ctx, updateMessageFlags,
		arg.ID,
		arg.OrgID,
		arg.IsRead,
		arg.IsStarred,
		arg.IsArchived,
		arg.IsTrashed,
	)
	return err
}

const updateThreadLastMessage = `-- name: UpdateThreadLastMessage :exec
UPDATE inbox_threads SET last_message_at = $2, message_count = message_count + 1, participant_addresses = $3 WHERE id = $1
`

type UpdateThreadLastMessageParams struct {
	ID                   uuid.UUID       `json:"id"`
	LastMessageAt        time.Time       `json:"last_message_at"`
	ParticipantAddresses json.RawMessage `json:"participant_addresses"`
}

func (q *Queries) UpdateThreadLastMessage(ctx context.Context, arg UpdateThreadLastMessageParams) error {
	_, err := q.db.Exec(ctx, updateThreadLastMessage, arg.ID, arg.LastMessageAt, arg.ParticipantAddresses)
	return err
}
