// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	OrgID      uuid.UUID          `json:"org_id"`
	DomainID   pgtype.UUID        `json:"domain_id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	KeyHash    string             `json:"key_hash"`
	Permission string             `json:"permission"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  time.Time          `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type AuditLog struct {
	ID           uuid.UUID   `json:"id"`
	OrgID        uuid.UUID   `json:"org_id"`
	UserID       pgtype.UUID `json:"user_id"`
	ApiKeyID     pgtype.UUID `json:"api_key_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	Metadata     []byte      `json:"metadata"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	CreatedAt    time.Time   `json:"created_at"`
}

type DnsRecord struct {
	ID         uuid.UUID          `json:"id"`
	DomainID   uuid.UUID          `json:"domain_id"`
	RecordType string             `json:"record_type"`
	Host       string             `json:"host"`
	Value      string             `json:"value"`
	Purpose    string             `json:"purpose"`
	Status     string             `json:"status"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type Domain struct {
	ID                    uuid.UUID          `json:"id"`
	OrgID                 uuid.UUID          `json:"org_id"`
	Name                  string             `json:"name"`
	Status                string             `json:"status"`
	Region                string             `json:"region"`
	DkimPrivateKey        pgtype.Text        `json:"dkim_private_key"`
	DkimSelector          string             `json:"dkim_selector"`
	OpenTracking          bool               `json:"open_tracking"`
	ClickTracking         bool               `json:"click_tracking"`
	CloudflareZoneID      pgtype.Text        `json:"cloudflare_zone_id"`
	CloudflareApiTokenEnc pgtype.Text        `json:"cloudflare_api_token_enc"`
	VerifiedAt            pgtype.Timestamptz `json:"verified_at"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
}

type Email struct {
	ID             uuid.UUID          `json:"id"`
	OrgID          uuid.UUID          `json:"org_id"`
	DomainID       uuid.UUID          `json:"domain_id"`
	ApiKeyID       pgtype.UUID        `json:"api_key_id"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	FromAddress    string             `json:"from_address"`
	FromName       pgtype.Text        `json:"from_name"`
	ToAddresses    json.RawMessage    `json:"to_addresses"`
	CcAddresses    []byte             `json:"cc_addresses"`
	BccAddresses   []byte             `json:"bcc_addresses"`
	ReplyTo        pgtype.Text        `json:"reply_to"`
	Subject        string             `json:"subject"`
	TextBodyKey    pgtype.Text        `json:"text_body_key"`
	HtmlBodyKey    pgtype.Text        `json:"html_body_key"`
	Headers        []byte             `json:"headers"`
	Tags           []byte             `json:"tags"`
	TemplateID     pgtype.UUID        `json:"template_id"`
	TemplateData   []byte             `json:"template_data"`
	Status         string             `json:"status"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	MessageID      pgtype.Text        `json:"message_id"`
	CreatedAt      time.Time          `json:"created_at"`
}

type EmailAttachment struct {
	ID          uuid.UUID `json:"id"`
	EmailID     uuid.UUID `json:"email_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	StorageKey  string    `json:"storage_key"`
	CreatedAt   time.Time `json:"created_at"`
}

type EmailEvent struct {
	ID         uuid.UUID   `json:"id"`
	EmailID    uuid.UUID   `json:"email_id"`
	OrgID      uuid.UUID   `json:"org_id"`
	EventType  string      `json:"event_type"`
	Recipient  string      `json:"recipient"`
	Metadata   []byte      `json:"metadata"`
	IpAddress  *netip.Addr `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
	OccurredAt time.Time   `json:"occurred_at"`
}

type InboxLabel struct {
	ID        uuid.UUID   `json:"id"`
	OrgID     uuid.UUID   `json:"org_id"`
	Name      string      `json:"name"`
	Color     pgtype.Text `json:"color"`
	CreatedAt time.Time   `json:"created_at"`
}

type InboxMessage struct {
	ID               uuid.UUID       `json:"id"`
	OrgID            uuid.UUID       `json:"org_id"`
	DomainID         uuid.UUID       `json:"domain_id"`
	ThreadID         pgtype.UUID     `json:"thread_id"`
	MessageIDHeader  pgtype.Text     `json:"message_id_header"`
	InReplyTo        pgtype.Text     `json:"in_reply_to"`
	ReferencesHeader pgtype.Text     `json:"references_header"`
	FromAddress      string          `json:"from_address"`
	FromName         pgtype.Text     `json:"from_name"`
	ToAddresses      json.RawMessage `json:"to_addresses"`
	CcAddresses      []byte          `json:"cc_addresses"`
	Subject          string          `json:"subject"`
	TextBodyKey      pgtype.Text     `json:"text_body_key"`
	HtmlBodyKey      pgtype.Text     `json:"html_body_key"`
	Snippet          pgtype.Text     `json:"snippet"`
	IsRead           bool            `json:"is_read"`
	IsStarred        bool            `json:"is_starred"`
	IsArchived       bool            `json:"is_archived"`
	IsTrashed        bool            `json:"is_trashed"`
	ReceivedAt       time.Time       `json:"received_at"`
	CreatedAt        time.Time       `json:"created_at"`
}

type InboxMessageAttachment struct {
	ID          uuid.UUID `json:"id"`
	MessageID   uuid.UUID `json:"message_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	StorageKey  string    `json:"storage_key"`
	CreatedAt   time.Time `json:"created_at"`
}

type InboxMessageLabel struct {
	MessageID uuid.UUID `json:"message_id"`
	LabelID   uuid.UUID `json:"label_id"`
}

type InboxThread struct {
	ID                   uuid.UUID       `json:"id"`
	OrgID                uuid.UUID       `json:"org_id"`
	DomainID             uuid.UUID       `json:"domain_id"`
	Subject              string          `json:"subject"`
	ParticipantAddresses json.RawMessage `json:"participant_addresses"`
	LastMessageAt        time.Time       `json:"last_message_at"`
	MessageCount         int32           `json:"message_count"`
	CreatedAt            time.Time       `json:"created_at"`
}

type IpPool struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	IpAddress     string             `json:"ip_address"`
	IsDedicated   bool               `json:"is_dedicated"`
	OrgID         pgtype.UUID        `json:"org_id"`
	WarmupPhase   int32              `json:"warmup_phase"`
	WarmupStarted pgtype.Timestamptz `json:"warmup_started"`
	DailyLimit    int32              `json:"daily_limit"`
	Status        string             `json:"status"`
	CreatedAt     time.Time          `json:"created_at"`
}

type OrgMember struct {
	ID        uuid.UUID   `json:"id"`
	OrgID     uuid.UUID   `json:"org_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      string      `json:"role"`
	InvitedBy pgtype.UUID `json:"invited_by"`
	JoinedAt  time.Time   `json:"joined_at"`
}

type Organization struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Plan           string    `json:"plan"`
	MonthlyLimit   int32     `json:"monthly_limit"`
	OverageEnabled bool      `json:"overage_enabled"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type PostfixVirtualDomain struct {
	Domain string `json:"domain"`
}

type PostfixVirtualMailbox struct {
	Domain string `json:"domain"`
}

type Suppression struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	Email     string    `json:"email"`
	Reason    string    `json:"reason"`
	Metadata  []byte    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
}

type Template struct {
	ID        uuid.UUID   `json:"id"`
	OrgID     uuid.UUID   `json:"org_id"`
	Name      string      `json:"name"`
	Subject   string      `json:"subject"`
	HtmlBody  string      `json:"html_body"`
	TextBody  pgtype.Text `json:"text_body"`
	Variables []byte      `json:"variables"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type UsageDaily struct {
	ID              uuid.UUID   `json:"id"`
	OrgID           uuid.UUID   `json:"org_id"`
	Date            pgtype.Date `json:"date"`
	EmailsSent      int32       `json:"emails_sent"`
	EmailsDelivered int32       `json:"emails_delivered"`
	EmailsBounced   int32       `json:"emails_bounced"`
	EmailsReceived  int32       `json:"emails_received"`
	ApiCalls        int32       `json:"api_calls"`
}

type UsageMonthly struct {
	ID            uuid.UUID   `json:"id"`
	OrgID         uuid.UUID   `json:"org_id"`
	Month         pgtype.Date `json:"month"`
	TotalSent     int32       `json:"total_sent"`
	TotalReceived int32       `json:"total_received"`
	TotalApiCalls int32       `json:"total_api_calls"`
	PlanLimit     int32       `json:"plan_limit"`
	OverageCount  int32       `json:"overage_count"`
}

type User struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	GoogleID    string             `json:"google_id"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type Webhook struct {
	ID        uuid.UUID       `json:"id"`
	OrgID     uuid.UUID       `json:"org_id"`
	Url       string          `json:"url"`
	Events    json.RawMessage `json:"events"`
	Secret    string          `json:"secret"`
	IsActive  bool            `json:"is_active"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type WebhookDelivery struct {
	ID             uuid.UUID          `json:"id"`
	WebhookID      uuid.UUID          `json:"webhook_id"`
	EventType      string             `json:"event_type"`
	Payload        json.RawMessage    `json:"payload"`
	ResponseStatus pgtype.Int4        `json:"response_status"`
	ResponseBody   pgtype.Text        `json:"response_body"`
	Attempt        int32              `json:"attempt"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	NextRetryAt    pgtype.Timestamptz `json:"next_retry_at"`
	Status         string             `json:"status"`
	CreatedAt      time.Time          `json:"created_at"`
}
