// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: org_members.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addOrgMember = `-- name: AddOrgMember :one
INSERT INTO org_members (org_id, user_id, role, invited_by)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, user_id, role, invited_by, joined_at
`

type AddOrgMemberParams struct {
	OrgID     uuid.UUID   `json:"org_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      string      `json:"role"`
	InvitedBy pgtype.UUID `json:"invited_by"`
}

func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, addOrgMember,
		arg.OrgID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
	)
	var i OrgMember
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
	)
	return i, err
}

const getOrgMember = `-- name: GetOrgMember :one
SELECT id, org_id, user_id, role, invited_by, joined_at FROM org_members WHERE org_id = $1 AND user_id = $2
`

type GetOrgMemberParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, getOrgMember, arg.OrgID, arg.UserID)
	var i OrgMember
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
	)
	return i, err
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT om.id, om.org_id, om.user_id, om.role, om.invited_by, om.joined_at, u.email, u.name, u.avatar_url
FROM org_members om
JOIN users u ON u.id = om.user_id
WHERE om.org_id = $1
ORDER BY om.joined_at
`

type ListOrgMembersRow struct {
	ID        uuid.UUID   `json:"id"`
	OrgID     uuid.UUID   `json:"org_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      string      `json:"role"`
	InvitedBy pgtype.UUID `json:"invited_by"`
	JoinedAt  time.Time   `json:"joined_at"`
	Email     string      `json:"email"`
	Name      string      `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) ListOrgMembers(ctx context.Context, orgID uuid.UUID) ([]ListOrgMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgMembersRow{}
	for rows.Next() {
		var i ListOrgMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.JoinedAt,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrgs = `-- name: ListUserOrgs :many
SELECT o.id, o.name, o.slug, o.plan, o.monthly_limit, o.overage_enabled, o.created_at, o.updated_at, om.role
FROM organizations o
JOIN org_members om ON om.org_id = o.id
WHERE om.user_id = $1
ORDER BY o.name
`

type ListUserOrgsRow struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Plan           string    `json:"plan"`
	MonthlyLimit   int32     `json:"monthly_limit"`
	OverageEnabled bool      `json:"overage_enabled"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Role           string    `json:"role"`
}

func (q *Queries) ListUserOrgs(ctx context.Context, userID uuid.UUID) ([]ListUserOrgsRow, error) {
	rows, err := q.db.Query(ctx, listUserOrgs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserOrgsRow{}
	for rows.Next() {
		var i ListUserOrgsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Plan,
			&i.MonthlyLimit,
			&i.OverageEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrgMember = `-- name: RemoveOrgMember :exec
DELETE FROM org_members WHERE org_id = $1 AND user_id = $2
`

type RemoveOrgMemberParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error {
	_, err := q.db.Exec(ctx, removeOrgMember, arg.OrgID, arg.UserID)
	return err
}

const updateOrgMemberRole = `-- name: UpdateOrgMemberRole :exec
UPDATE org_members SET role = $3 WHERE org_id = $1 AND user_id = $2
`

type UpdateOrgMemberRoleParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) UpdateOrgMemberRole(ctx context.Context, arg UpdateOrgMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateOrgMemberRole, arg.OrgID, arg.UserID, arg.Role)
	return err
}
