// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug, plan, monthly_limit)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, plan, monthly_limit, overage_enabled, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name         string `json:"name"`
	Slug         string `json:"slug"`
	Plan         string `json:"plan"`
	MonthlyLimit int32  `json:"monthly_limit"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.Slug,
		arg.Plan,
		arg.MonthlyLimit,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.MonthlyLimit,
		&i.OverageEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, slug, plan, monthly_limit, overage_enabled, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.MonthlyLimit,
		&i.OverageEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, plan, monthly_limit, overage_enabled, created_at, updated_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.MonthlyLimit,
		&i.OverageEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET name = $2, plan = $3, monthly_limit = $4, overage_enabled = $5
WHERE id = $1
RETURNING id, name, slug, plan, monthly_limit, overage_enabled, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Plan           string    `json:"plan"`
	MonthlyLimit   int32     `json:"monthly_limit"`
	OverageEnabled bool      `json:"overage_enabled"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Plan,
		arg.MonthlyLimit,
		arg.OverageEnabled,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.MonthlyLimit,
		&i.OverageEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationName = `-- name: UpdateOrganizationName :one
UPDATE organizations SET name = $2 WHERE id = $1 RETURNING id, name, slug, plan, monthly_limit, overage_enabled, created_at, updated_at
`

type UpdateOrganizationNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateOrganizationName(ctx context.Context, arg UpdateOrganizationNameParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationName, arg.ID, arg.Name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.MonthlyLimit,
		&i.OverageEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
