// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddMessageLabel(ctx context.Context, arg AddMessageLabelParams) error
	AddOrgMember(ctx context.Context, arg AddOrgMemberParams) (OrgMember, error)
	CheckSuppressed(ctx context.Context, arg CheckSuppressedParams) (bool, error)
	CountAuditLogs(ctx context.Context, orgID uuid.UUID) (int64, error)
	CountEmailEventsByOrg(ctx context.Context, orgID uuid.UUID) (int64, error)
	CountEmailEventsByType(ctx context.Context, arg CountEmailEventsByTypeParams) ([]CountEmailEventsByTypeRow, error)
	CountEmailsByOrg(ctx context.Context, orgID uuid.UUID) (int64, error)
	CountSuppressionsByOrg(ctx context.Context, orgID uuid.UUID) (int64, error)
	CountThreads(ctx context.Context, orgID uuid.UUID) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateDNSRecord(ctx context.Context, arg CreateDNSRecordParams) (DnsRecord, error)
	CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error)
	CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error)
	CreateEmailEvent(ctx context.Context, arg CreateEmailEventParams) (EmailEvent, error)
	// Messages
	CreateInboxMessage(ctx context.Context, arg CreateInboxMessageParams) (InboxMessage, error)
	// Labels
	CreateLabel(ctx context.Context, arg CreateLabelParams) (InboxLabel, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateSuppression(ctx context.Context, arg CreateSuppressionParams) (Suppression, error)
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error)
	// Threads
	CreateThread(ctx context.Context, arg CreateThreadParams) (InboxThread, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error)
	DeleteDNSRecordsByDomain(ctx context.Context, domainID uuid.UUID) error
	DeleteDomain(ctx context.Context, arg DeleteDomainParams) error
	DeleteInboxMessage(ctx context.Context, arg DeleteInboxMessageParams) error
	DeleteLabel(ctx context.Context, arg DeleteLabelParams) error
	DeleteSuppression(ctx context.Context, arg DeleteSuppressionParams) error
	DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) error
	DeleteThread(ctx context.Context, arg DeleteThreadParams) error
	DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) error
	FindMessageByMessageID(ctx context.Context, arg FindMessageByMessageIDParams) (InboxMessage, error)
	FindThreadBySubjectAndDomain(ctx context.Context, arg FindThreadBySubjectAndDomainParams) (InboxThread, error)
	GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetAuditLog(ctx context.Context, arg GetAuditLogParams) (AuditLog, error)
	GetCurrentMonthUsage(ctx context.Context, orgID uuid.UUID) (GetCurrentMonthUsageRow, error)
	GetDomain(ctx context.Context, arg GetDomainParams) (Domain, error)
	GetDomainByName(ctx context.Context, arg GetDomainByNameParams) (Domain, error)
	GetEmail(ctx context.Context, arg GetEmailParams) (Email, error)
	GetEmailByIdempotencyKey(ctx context.Context, arg GetEmailByIdempotencyKeyParams) (Email, error)
	GetEmailOrgID(ctx context.Context, id uuid.UUID) (GetEmailOrgIDRow, error)
	GetInboxMessage(ctx context.Context, arg GetInboxMessageParams) (InboxMessage, error)
	GetMonthlyUsageHistory(ctx context.Context, arg GetMonthlyUsageHistoryParams) ([]UsageMonthly, error)
	GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error)
	GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetSuppression(ctx context.Context, arg GetSuppressionParams) (Suppression, error)
	GetTemplate(ctx context.Context, arg GetTemplateParams) (Template, error)
	GetTemplateByName(ctx context.Context, arg GetTemplateByNameParams) (Template, error)
	GetThread(ctx context.Context, arg GetThreadParams) (InboxThread, error)
	GetUsageDaily(ctx context.Context, arg GetUsageDailyParams) ([]UsageDaily, error)
	GetUsageSummary(ctx context.Context, arg GetUsageSummaryParams) (GetUsageSummaryRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
	GetVerifiedDomainByName(ctx context.Context, arg GetVerifiedDomainByNameParams) (Domain, error)
	GetWebhook(ctx context.Context, arg GetWebhookParams) (Webhook, error)
	GetWebhookByDeliveryID(ctx context.Context, id uuid.UUID) (Webhook, error)
	GetWebhookDelivery(ctx context.Context, id uuid.UUID) (WebhookDelivery, error)
	ListAPIKeysByOrg(ctx context.Context, orgID uuid.UUID) ([]ApiKey, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListDNSRecordsByDomain(ctx context.Context, domainID uuid.UUID) ([]DnsRecord, error)
	ListDomainsByOrg(ctx context.Context, orgID uuid.UUID) ([]Domain, error)
	ListEmailEvents(ctx context.Context, emailID uuid.UUID) ([]EmailEvent, error)
	ListEmailEventsByOrg(ctx context.Context, arg ListEmailEventsByOrgParams) ([]EmailEvent, error)
	ListEmailsByOrg(ctx context.Context, arg ListEmailsByOrgParams) ([]Email, error)
	ListLabelsByOrg(ctx context.Context, orgID uuid.UUID) ([]InboxLabel, error)
	ListMessageLabels(ctx context.Context, arg ListMessageLabelsParams) ([]InboxLabel, error)
	ListMessagesByThread(ctx context.Context, arg ListMessagesByThreadParams) ([]InboxMessage, error)
	ListOrgMembers(ctx context.Context, orgID uuid.UUID) ([]ListOrgMembersRow, error)
	ListSuppressionsByOrg(ctx context.Context, arg ListSuppressionsByOrgParams) ([]Suppression, error)
	ListTemplatesByOrg(ctx context.Context, orgID uuid.UUID) ([]Template, error)
	ListThreads(ctx context.Context, arg ListThreadsParams) ([]InboxThread, error)
	ListUserOrgs(ctx context.Context, userID uuid.UUID) ([]ListUserOrgsRow, error)
	ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error)
	ListWebhooksByOrg(ctx context.Context, orgID uuid.UUID) ([]Webhook, error)
	ListWebhooksByOrgAndEvent(ctx context.Context, arg ListWebhooksByOrgAndEventParams) ([]Webhook, error)
	MarkMessageRead(ctx context.Context, arg MarkMessageReadParams) error
	RemoveMessageLabel(ctx context.Context, arg RemoveMessageLabelParams) error
	RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]InboxMessage, error)
	UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateDNSRecordStatus(ctx context.Context, arg UpdateDNSRecordStatusParams) error
	UpdateDomainCloudflare(ctx context.Context, arg UpdateDomainCloudflareParams) error
	UpdateDomainSettings(ctx context.Context, arg UpdateDomainSettingsParams) (Domain, error)
	UpdateDomainStatus(ctx context.Context, arg UpdateDomainStatusParams) error
	UpdateEmailStatus(ctx context.Context, arg UpdateEmailStatusParams) error
	UpdateLabel(ctx context.Context, arg UpdateLabelParams) (InboxLabel, error)
	UpdateMessageFlags(ctx context.Context, arg UpdateMessageFlagsParams) error
	UpdateOrgMemberRole(ctx context.Context, arg UpdateOrgMemberRoleParams) error
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateOrganizationName(ctx context.Context, arg UpdateOrganizationNameParams) (Organization, error)
	UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error)
	UpdateThreadLastMessage(ctx context.Context, arg UpdateThreadLastMessageParams) error
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error)
	UpdateWebhookDelivery(ctx context.Context, arg UpdateWebhookDeliveryParams) error
	UpsertUsageDaily(ctx context.Context, arg UpsertUsageDailyParams) error
	UpsertUsageMonthly(ctx context.Context, arg UpsertUsageMonthlyParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
