// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suppressions.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const checkSuppressed = `-- name: CheckSuppressed :one
SELECT EXISTS(SELECT 1 FROM suppressions WHERE org_id = $1 AND email = $2) AS is_suppressed
`

type CheckSuppressedParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Email string    `json:"email"`
}

func (q *Queries) CheckSuppressed(ctx context.Context, arg CheckSuppressedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkSuppressed, arg.OrgID, arg.Email)
	var is_suppressed bool
	err := row.Scan(&is_suppressed)
	return is_suppressed, err
}

const countSuppressionsByOrg = `-- name: CountSuppressionsByOrg :one
SELECT COUNT(*) FROM suppressions WHERE org_id = $1
`

func (q *Queries) CountSuppressionsByOrg(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppressionsByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSuppression = `-- name: CreateSuppression :one
INSERT INTO suppressions (org_id, email, reason, metadata)
VALUES ($1, $2, $3, $4)
ON CONFLICT (org_id, email) DO NOTHING
RETURNING id, org_id, email, reason, metadata, created_at
`

type CreateSuppressionParams struct {
	OrgID    uuid.UUID `json:"org_id"`
	Email    string    `json:"email"`
	Reason   string    `json:"reason"`
	Metadata []byte    `json:"metadata"`
}

func (q *Queries) CreateSuppression(ctx context.Context, arg CreateSuppressionParams) (Suppression, error) {
	row := q.db.QueryRow(ctx, createSuppression,
		arg.OrgID,
		arg.Email,
		arg.Reason,
		arg.Metadata,
	)
	var i Suppression
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Reason,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSuppression = `-- name: DeleteSuppression :exec
DELETE FROM suppressions WHERE id = $1 AND org_id = $2
`

type DeleteSuppressionParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteSuppression(ctx context.Context, arg DeleteSuppressionParams) error {
	_, err := q.db.Exec(ctx, deleteSuppression, arg.ID, arg.OrgID)
	return err
}

const getSuppression = `-- name: GetSuppression :one
SELECT id, org_id, email, reason, metadata, created_at FROM suppressions WHERE org_id = $1 AND email = $2
`

type GetSuppressionParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Email string    `json:"email"`
}

func (q *Queries) GetSuppression(ctx context.Context, arg GetSuppressionParams) (Suppression, error) {
	row := q.db.QueryRow(ctx, getSuppression, arg.OrgID, arg.Email)
	var i Suppression
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Reason,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listSuppressionsByOrg = `-- name: ListSuppressionsByOrg :many
SELECT id, org_id, email, reason, metadata, created_at FROM suppressions WHERE org_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListSuppressionsByOrgParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListSuppressionsByOrg(ctx context.Context, arg ListSuppressionsByOrgParams) ([]Suppression, error) {
	rows, err := q.db.Query(ctx, listSuppressionsByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Suppression{}
	for rows.Next() {
		var i Suppression
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Reason,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
