// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (org_id, name, subject, html_body, text_body, variables)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, name, subject, html_body, text_body, variables, created_at, updated_at
`

type CreateTemplateParams struct {
	OrgID     uuid.UUID   `json:"org_id"`
	Name      string      `json:"name"`
	Subject   string      `json:"subject"`
	HtmlBody  string      `json:"html_body"`
	TextBody  pgtype.Text `json:"text_body"`
	Variables []byte      `json:"variables"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.OrgID,
		arg.Name,
		arg.Subject,
		arg.HtmlBody,
		arg.TextBody,
		arg.Variables,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.Variables,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE id = $1 AND org_id = $2
`

type DeleteTemplateParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteTemplate, arg.ID, arg.OrgID)
	return err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, org_id, name, subject, html_body, text_body, variables, created_at, updated_at FROM templates WHERE id = $1 AND org_id = $2
`

type GetTemplateParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetTemplate(ctx context.Context, arg GetTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplate, arg.ID, arg.OrgID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.Variables,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByName = `-- name: GetTemplateByName :one
SELECT id, org_id, name, subject, html_body, text_body, variables, created_at, updated_at FROM templates WHERE org_id = $1 AND name = $2
`

type GetTemplateByNameParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

func (q *Queries) GetTemplateByName(ctx context.Context, arg GetTemplateByNameParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByName, arg.OrgID, arg.Name)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.Variables,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplatesByOrg = `-- name: ListTemplatesByOrg :many
SELECT id, org_id, name, subject, html_body, text_body, variables, created_at, updated_at FROM templates WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListTemplatesByOrg(ctx context.Context, orgID uuid.UUID) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Subject,
			&i.HtmlBody,
			&i.TextBody,
			&i.Variables,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET name = $3, subject = $4, html_body = $5, text_body = $6, variables = $7
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, subject, html_body, text_body, variables, created_at, updated_at
`

type UpdateTemplateParams struct {
	ID        uuid.UUID   `json:"id"`
	OrgID     uuid.UUID   `json:"org_id"`
	Name      string      `json:"name"`
	Subject   string      `json:"subject"`
	HtmlBody  string      `json:"html_body"`
	TextBody  pgtype.Text `json:"text_body"`
	Variables []byte      `json:"variables"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Subject,
		arg.HtmlBody,
		arg.TextBody,
		arg.Variables,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.Variables,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
