// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (org_id, url, events, secret, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, url, events, secret, is_active, created_at, updated_at
`

type CreateWebhookParams struct {
	OrgID    uuid.UUID       `json:"org_id"`
	Url      string          `json:"url"`
	Events   json.RawMessage `json:"events"`
	Secret   string          `json:"secret"`
	IsActive bool            `json:"is_active"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.OrgID,
		arg.Url,
		arg.Events,
		arg.Secret,
		arg.IsActive,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.Events,
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (webhook_id, event_type, payload, status)
VALUES ($1, $2, $3, $4)
RETURNING id, webhook_id, event_type, payload, response_status, response_body, attempt, delivered_at, next_retry_at, status, created_at
`

type CreateWebhookDeliveryParams struct {
	WebhookID uuid.UUID       `json:"webhook_id"`
	EventType string          `json:"event_type"`
	Payload   json.RawMessage `json:"payload"`
	Status    string          `json:"status"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.WebhookID,
		arg.EventType,
		arg.Payload,
		arg.Status,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventType,
		&i.Payload,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.Attempt,
		&i.DeliveredAt,
		&i.NextRetryAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = $1 AND org_id = $2
`

type DeleteWebhookParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) error {
	_, err := q.db.Exec(ctx, deleteWebhook, arg.ID, arg.OrgID)
	return err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, org_id, url, events, secret, is_active, created_at, updated_at FROM webhooks WHERE id = $1 AND org_id = $2
`

type GetWebhookParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetWebhook(ctx context.Context, arg GetWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, arg.ID, arg.OrgID)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.Events,
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookByDeliveryID = `-- name: GetWebhookByDeliveryID :one
SELECT w.id, w.org_id, w.url, w.events, w.secret, w.is_active, w.created_at, w.updated_at FROM webhooks w
JOIN webhook_deliveries wd ON wd.webhook_id = w.id
WHERE wd.id = $1
`

func (q *Queries) GetWebhookByDeliveryID(ctx context.Context, id uuid.UUID) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhookByDeliveryID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.Events,
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, webhook_id, event_type, payload, response_status, response_body, attempt, delivered_at, next_retry_at, status, created_at FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) GetWebhookDelivery(ctx context.Context, id uuid.UUID) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventType,
		&i.Payload,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.Attempt,
		&i.DeliveredAt,
		&i.NextRetryAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, webhook_id, event_type, payload, response_status, response_body, attempt, delivered_at, next_retry_at, status, created_at FROM webhook_deliveries WHERE webhook_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListWebhookDeliveriesParams struct {
	WebhookID uuid.UUID `json:"webhook_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, arg.WebhookID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventType,
			&i.Payload,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.Attempt,
			&i.DeliveredAt,
			&i.NextRetryAt,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByOrg = `-- name: ListWebhooksByOrg :many
SELECT id, org_id, url, events, secret, is_active, created_at, updated_at FROM webhooks WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListWebhooksByOrg(ctx context.Context, orgID uuid.UUID) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Url,
			&i.Events,
			&i.Secret,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByOrgAndEvent = `-- name: ListWebhooksByOrgAndEvent :many
SELECT id, org_id, url, events, secret, is_active, created_at, updated_at FROM webhooks WHERE org_id = $1 AND is_active = true AND events @> $2
`

type ListWebhooksByOrgAndEventParams struct {
	OrgID  uuid.UUID       `json:"org_id"`
	Events json.RawMessage `json:"events"`
}

func (q *Queries) ListWebhooksByOrgAndEvent(ctx context.Context, arg ListWebhooksByOrgAndEventParams) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksByOrgAndEvent, arg.OrgID, arg.Events)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Url,
			&i.Events,
			&i.Secret,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks SET url = $3, events = $4, is_active = $5
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, url, events, secret, is_active, created_at, updated_at
`

type UpdateWebhookParams struct {
	ID       uuid.UUID       `json:"id"`
	OrgID    uuid.UUID       `json:"org_id"`
	Url      string          `json:"url"`
	Events   json.RawMessage `json:"events"`
	IsActive bool            `json:"is_active"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.ID,
		arg.OrgID,
		arg.Url,
		arg.Events,
		arg.IsActive,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.Events,
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhookDelivery = `-- name: UpdateWebhookDelivery :exec
UPDATE webhook_deliveries
SET response_status = $2,
    response_body = $3,
    attempt = $4,
    status = $5,
    delivered_at = CASE WHEN $5 = 'delivered' THEN NOW() ELSE delivered_at END,
    next_retry_at = $6
WHERE id = $1
`

type UpdateWebhookDeliveryParams struct {
	ID             uuid.UUID          `json:"id"`
	ResponseStatus pgtype.Int4        `json:"response_status"`
	ResponseBody   pgtype.Text        `json:"response_body"`
	Attempt        int32              `json:"attempt"`
	Status         string             `json:"status"`
	NextRetryAt    pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) UpdateWebhookDelivery(ctx context.Context, arg UpdateWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, updateWebhookDelivery,
		arg.ID,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.Attempt,
		arg.Status,
		arg.NextRetryAt,
	)
	return err
}
